In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid") # this will make the plot look better

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
df = pd.read_csv("../data/raw/tech_employment_2000_2025.csv")

print("Dataset loaded.")
df.head()

Dataset loaded.

,company,year,employees_start,employees_end,new_hires,layoffs,net_change,hiring_rate_pct,attrition_rate_pct,revenue_billions_usd,stock_price_change_pct,gdp_growth_us_pct,unemployment_rate_us_pct,is_estimated,confidence_level,data_quality_score
0,AMD,2001,13387,14400,2083,1070,1013,15.6,8.0,3.89,25.1,1.0,4.7,False,Medium,95
1,AMD,2002,14400,12500,0,1900,-1900,0.0,13.2,2.70,42.8,1.7,5.8,False,Medium,95
2,AMD,2003,12500,12000,0,500,-500,0.0,4.0,3.52,-1.8,2.8,6.0,False,Medium,95
3,AMD,2004,12000,11700,60,360,-300,0.5,3.0,5.00,-18.6,3.8,5.5,False,Medium,95
4,AMD,2005,11700,9860,0,1840,-1840,0.0,15.7,5.85,15.2,3.5,5.1,False,Medium,95

In [3]:
df.shape # that is 532 rows and 16 columns

(532, 16)

In [4]:
df.columns

Index(['company', 'year', 'employees_start', 'employees_end', 'new_hires',
       'layoffs', 'net_change', 'hiring_rate_pct', 'attrition_rate_pct',
       'revenue_billions_usd', 'stock_price_change_pct', 'gdp_growth_us_pct',
       'unemployment_rate_us_pct', 'is_estimated', 'confidence_level',
       'data_quality_score'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 532 entries, 0 to 531
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   company                   532 non-null    str
 1   year                      532 non-null    int64
 2   employees_start           532 non-null    int64
 3   employees_end             532 non-null    int64
 4   new_hires                 532 non-null    int64
 5   layoffs                   532 non-null    int64
 6   net_change                532 non-null    int64
 7   hiring_rate_pct           532 non-null    float64
 8   attrition_rate_pct        532 non-null    float64
 9   revenue_billions_usd      532 non-null    float64
 10  stock_price_change_pct    532 non-null    float64
 11  gdp_growth_us_pct         532 non-null    float64
 12  unemployment_rate_us_pct  532 non-null    float64
 13  is_estimated              532 non-null    bool
 14  confidence_level          532 non-null    str
 15  data_quality_score        532 non-null    int64
dtypes: bool(1), float64(6), int64(7), str(2)
memory usage: 63.0 KB

In [6]:
yearly_summary = (
    df.groupby("year")[["new_hires", "layoffs", "net_change"]]
      .sum()
      .reset_index()
)

yearly_summary.head()

   year  new_hires  layoffs  net_change
0  2001      30830    18530       12300
1  2002      17793    19774       -1981
2  2003      15146     7199        7947
3  2004      30435     7393       23042
4  2005      36474     9630       26844

In [7]:
macro_summary = (
    df.groupby("year")[["gdp_growth_us_pct", "unemployment_rate_us_pct"]]
        .mean()
        .reset_index()
)

macro_summary.head()

   year  gdp_growth_us_pct  unemployment_rate_us_pct
0  2001                1.0                       4.7
1  2002                1.7                       5.8
2  2003                2.8                       6.0
3  2004                3.8                       5.5
4  2005                3.5                       5.1

In [8]:
yearly_summary = yearly_summary.merge(macro_summary, on="year")
yearly_summary.head()

,year,new_hires,layoffs,net_change,gdp_growth_us_pct,unemployment_rate_us_pct
0,2001,30830,18530,12300,1.0,4.7
1,2002,17793,19774,-1981,1.7,5.8
2,2003,15146,7199,7947,2.8,6.0
3,2004,30435,7393,23042,3.8,5.5
4,2005,36474,9630,26844,3.5,5.1

In [9]:
company_summary = (
    df.groupby("company")
      .agg({
          "new_hires": "sum",
          "layoffs": "sum",
          "hiring_rate_pct": "mean",
          "attrition_rate_pct": "mean",
          "net_change": "std",
      })
      .reset_index()
)

company_summary.head()

,company,new_hires,layoffs,hiring_rate_pct,attrition_rate_pct,net_change
0,AMD,37850,22237,11.328000,6.344000,2904.927855
1,Adobe,40071,12578,15.048000,4.120000,1192.800749
2,Airbnb,9909,2426,56.976471,3.576471,511.710885
3,Alphabet,246281,63848,28.077273,4.104545,9986.019087
4,Amazon,1949387,418387,29.184000,4.252000,122479.471069

In [10]:
company_summary.sort_values("net_change", ascending=False).head(5)

,company,new_hires,layoffs,hiring_rate_pct,attrition_rate_pct,net_change
4,Amazon,1949387,418387,29.184000,4.252000,122479.471069
11,Microsoft,305301,116401,11.932000,4.300000,10552.609472
3,Alphabet,246281,63848,28.077273,4.104545,9986.019087
22,Tesla,167821,29863,54.200000,3.622727,9822.631408
10,Meta,112761,34438,47.275000,4.565000,7292.011016

In [11]:
yearly_summary.to_csv("../data/processed/yearly_summary.csv", index=False)

In [12]:
import os
os.listdir("../data/processed")

['yearly_summary.csv', 'company_year_dataset.csv', 'company_summary.csv']

In [13]:
company_summary.to_csv("../data/processed/company_summary.csv", index=False)

In [14]:
os.listdir("../data/processed")

['yearly_summary.csv', 'company_year_dataset.csv', 'company_summary.csv']

In [15]:
company_year_dataset = df[[
    "company",
    "year",
    "new_hires",
    "layoffs",
    "net_change",
    "hiring_rate_pct",
    "attrition_rate_pct",
    "gdp_growth_us_pct",
    "unemployment_rate_us_pct"
]].copy()

company_year_dataset.head()

,company,year,new_hires,layoffs,net_change,hiring_rate_pct,attrition_rate_pct,gdp_growth_us_pct,unemployment_rate_us_pct
0,AMD,2001,2083,1070,1013,15.6,8.0,1.0,4.7
1,AMD,2002,0,1900,-1900,0.0,13.2,1.7,5.8
2,AMD,2003,0,500,-500,0.0,4.0,2.8,6.0
3,AMD,2004,60,360,-300,0.5,3.0,3.8,5.5
4,AMD,2005,0,1840,-1840,0.0,15.7,3.5,5.1

In [16]:
company_year_dataset.to_csv("../data/processed/company_year_dataset.csv", index=False)

In [17]:
os.listdir("../data/processed")

['yearly_summary.csv', 'company_year_dataset.csv', 'company_summary.csv']

In [18]:
os.listdir("../data/raw")

['.DS_Store', 'tech_employment_2000_2025.csv']

In [19]:
os.listdir("../data/processed")

['yearly_summary.csv', 'company_year_dataset.csv', 'company_summary.csv']